from abc import ABC, abstractmethod
from typing import List, Optional
from .entities import Item
from .entities import Pin
from .entities import Account

class ItemRepository(ABC):
    @abstractmethod
    async def create(self, item: Item) -> Item: ...

    @abstractmethod
    async def get(self, item_id: str) -> Optional[Item]: ...

    @abstractmethod
    async def list(self) -> List[Item]: ...

    @abstractmethod
    async def update(self, item: Item) -> Item: ...

    @abstractmethod
    async def delete(self, item_id: str) -> bool: ...

class PinRepository(ABC):
    @abstractmethod
    async def create(self, pin: Pin) -> Pin: ...

    @abstractmethod
    async def get(self, pin_id: str) -> Optional[Pin]: ...

    @abstractmethod
    async def list(self) -> List[Pin]: ...

    @abstractmethod
    async def update(self, pin: Pin) -> Pin: ...

    @abstractmethod
    async def delete(self, pin_id: str) -> bool: ...

class AccountRepository(ABC):
    @abstractmethod
    async def create(self, account: Account) -> Account: ...
    @abstractmethod
    async def get_by_id(self, account_id: str) -> Optional[Account]: ...
    @abstractmethod
    async def get_by_email(self, email: str) -> Optional[Account]: ...
    @abstractmethod
    async def list(self) -> List[Account]: ...
    @abstractmethod
    async def update(self, account: Account) -> Account: ...
    @abstractmethod
    async def delete(self, account_id: str) -> bool: ...
